timeout: 0
serial: yes

/vibix
    protocol: limine
    kernel_path: boot():/boot/vibix
    module_path: boot():/boot/userspace_init.elf
    module_path: boot():/boot/userspace_hello.elf
    module_path: boot():/boot/rootfs.tar
    module_path: boot():/boot/ld-musl-x86_64.so.1
    module_path: boot():/boot/stub_interp.elf
