//! Integration test for #764: dynamic-linker-stub ELF integration test.
//!
//! Verifies the demand-paged ELF loader's PT_INTERP handling end-to-end:
//! a synthesized main ELF whose `PT_INTERP` names a stub interpreter
//! (`stub_interp.elf`, generated by xtask and loaded as a Limine module)
//! is passed through `load_user_elf_with_vmas`. The test asserts:
//!
//! 1. The interpreter is found and loaded at `INTERP_LOAD_BASE`.
//! 2. `LoadedImage::interp_entry` is set to the interpreter's
//!    `e_entry + INTERP_LOAD_BASE`.
//! 3. `LoadedImage::interp_base` equals `INTERP_LOAD_BASE`.
//! 4. The main binary's `PT_LOAD` segments are registered as VMAs in the
//!    address space (demand-paged, not eagerly faulted).
//! 5. The effective entry point (which `exec_atomic` would use) is
//!    `interp_entry`, not the main binary's entry.
//!
//! This is the capstone test for the ELF loader workstream (RFC 0007
//! Demand-paged execve, issues #761, #762, #763).

#![no_std]
#![no_main]

extern crate alloc;

use alloc::vec;
use alloc::vec::Vec;
use core::panic::PanicInfo;

use vibix::mem::addrspace::AddressSpace;
use vibix::mem::loader::{LoadedImage, INTERP_LOAD_BASE};
use vibix::{
    exit_qemu, serial_println,
    test_harness::{test_panic_handler, Testable},
    QemuExitCode,
};

#[no_mangle]
pub extern "C" fn _start() -> ! {
    vibix::init();
    vibix::task::init();
    x86_64::instructions::interrupts::enable();
    run_tests();
    exit_qemu(QemuExitCode::Success);
}

#[panic_handler]
fn panic(info: &PanicInfo) -> ! {
    test_panic_handler(info)
}

fn run_tests() {
    let tests: &[(&str, &dyn Testable)] = &[
        (
            "dynlinker_stub_loads_interpreter",
            &(dynlinker_stub_loads_interpreter as fn()),
        ),
        (
            "dynlinker_stub_main_segments_registered",
            &(dynlinker_stub_main_segments_registered as fn()),
        ),
        (
            "dynlinker_stub_effective_entry_is_interp",
            &(dynlinker_stub_effective_entry_is_interp as fn()),
        ),
    ];
    serial_println!("running {} tests", tests.len());
    for (name, t) in tests {
        serial_println!("test {name}");
        t.run();
    }
}

// --- ELF64 synthesis helpers ------------------------------------------------

const EHDR_SIZE: usize = 0x40;
const PHDR_SIZE: usize = 0x38;

fn put16(bytes: &mut [u8], offset: usize, value: u16) {
    bytes[offset..offset + 2].copy_from_slice(&value.to_le_bytes());
}

fn put32(bytes: &mut [u8], offset: usize, value: u32) {
    bytes[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
}

fn put64(bytes: &mut [u8], offset: usize, value: u64) {
    bytes[offset..offset + 8].copy_from_slice(&value.to_le_bytes());
}

/// Synthesize a minimal ELF64 with a `PT_INTERP` segment naming the musl
/// dynamic linker. Layout:
///
///   EHDR | PHDR[0]=PT_INTERP | PHDR[1]=PT_LOAD(rx) | PHDR[2]=PT_LOAD(rw) | interp path
///
/// The `PT_LOAD` segments have `p_filesz == 0` (no file content to back them;
/// the demand-paging layer will register zero-length file VMAs and `.bss`-style
/// anon VMAs covering `p_memsz`). This is sufficient for verifying the loader's
/// VMA registration and interpreter resolution without needing real code bytes.
fn build_main_elf_with_interp(interp_path: &[u8]) -> Vec<u8> {
    let phdr_count: usize = 3;
    let phdr_table_size = phdr_count * PHDR_SIZE;
    let path_offset = EHDR_SIZE + phdr_table_size;
    // Include null terminator.
    let total = path_offset + interp_path.len() + 1;

    let mut bytes = vec![0u8; total];

    // ELF magic + class/data/version.
    bytes[0..4].copy_from_slice(&[0x7f, b'E', b'L', b'F']);
    bytes[4] = 2; // ELFCLASS64
    bytes[5] = 1; // little-endian
    bytes[6] = 1; // ELF v1
    put16(&mut bytes, 16, 2); // ET_EXEC
    put16(&mut bytes, 18, 0x3e); // x86_64
    put32(&mut bytes, 20, 1); // EV_CURRENT
    put64(&mut bytes, 24, 0x40_1000); // e_entry (within PT_LOAD[0])
    put64(&mut bytes, 32, EHDR_SIZE as u64); // e_phoff
    put16(&mut bytes, 52, EHDR_SIZE as u16); // e_ehsize
    put16(&mut bytes, 54, PHDR_SIZE as u16); // e_phentsize
    put16(&mut bytes, 56, phdr_count as u16); // e_phnum

    // PHDR 0: PT_INTERP — interpreter path.
    let p0 = EHDR_SIZE;
    put32(&mut bytes, p0, 3); // PT_INTERP
    put64(&mut bytes, p0 + 8, path_offset as u64); // p_offset
    put64(&mut bytes, p0 + 32, (interp_path.len() + 1) as u64); // p_filesz
    put64(&mut bytes, p0 + 40, (interp_path.len() + 1) as u64); // p_memsz

    // PHDR 1: PT_LOAD RX (text) — covers entry 0x401000.
    // p_filesz = 0 means no file backing; the entire memsz is .bss-like.
    let p1 = EHDR_SIZE + PHDR_SIZE;
    put32(&mut bytes, p1, 1); // PT_LOAD
    put32(&mut bytes, p1 + 4, 5); // PF_R | PF_X
    put64(&mut bytes, p1 + 16, 0x40_0000); // p_vaddr (page-aligned)
    put64(&mut bytes, p1 + 40, 0x2000); // p_memsz = 8 KiB

    // PHDR 2: PT_LOAD RW (data/bss).
    let p2 = EHDR_SIZE + 2 * PHDR_SIZE;
    put32(&mut bytes, p2, 1); // PT_LOAD
    put32(&mut bytes, p2 + 4, 6); // PF_R | PF_W
    put64(&mut bytes, p2 + 16, 0x40_2000); // p_vaddr (page-aligned)
    put64(&mut bytes, p2 + 40, 0x1000); // p_memsz = 4 KiB

    // Write the interpreter path (null-terminated) at `path_offset`.
    bytes[path_offset..path_offset + interp_path.len()].copy_from_slice(interp_path);
    bytes[path_offset + interp_path.len()] = 0;

    bytes
}

/// Call `load_user_elf_with_vmas` on a synthesized main ELF whose PT_INTERP
/// names the stub interpreter (loaded as a Limine module). Returns the
/// `LoadedImage` and the `AddressSpace` for further inspection.
fn load_dynlinked_elf() -> (LoadedImage, AddressSpace) {
    let bytes = build_main_elf_with_interp(b"/boot/stub_interp.elf");
    // Leak so the demand-paged loader can hold a &'static [u8].
    let leaked: &'static [u8] = bytes.leak();

    let mut aspace = AddressSpace::try_new_empty().expect("failed to allocate AddressSpace");
    let pml4 = aspace.page_table_frame();

    let image = vibix::mem::loader::load_user_elf_with_vmas(leaked, pml4, &mut aspace)
        .expect("load_user_elf_with_vmas failed for dynlinked ELF");

    (image, aspace)
}

// --- Test functions ---------------------------------------------------------

/// Verify that the interpreter is found among Limine modules and its
/// metadata is correctly recorded in the `LoadedImage`.
fn dynlinker_stub_loads_interpreter() {
    let (image, _aspace) = load_dynlinked_elf();

    // interp_entry must be set (the stub has e_entry = 0x80).
    let interp_entry = image
        .interp_entry
        .expect("interp_entry is None — interpreter was not loaded");
    serial_println!("  interp_entry = {:#x}", interp_entry.as_u64());

    // interp_base must equal INTERP_LOAD_BASE.
    let interp_base = image
        .interp_base
        .expect("interp_base is None — interpreter was not loaded");
    assert_eq!(
        interp_base, INTERP_LOAD_BASE,
        "interp_base ({:#x}) != INTERP_LOAD_BASE ({:#x})",
        interp_base, INTERP_LOAD_BASE
    );
    serial_println!("  interp_base = {:#x}", interp_base);

    // The interpreter entry must equal INTERP_LOAD_BASE + stub's e_entry (0x80).
    let expected_interp_entry = INTERP_LOAD_BASE + 0x80;
    assert_eq!(
        interp_entry.as_u64(),
        expected_interp_entry,
        "interp_entry ({:#x}) != expected ({:#x})",
        interp_entry.as_u64(),
        expected_interp_entry,
    );

    // The main binary's own entry must still be at 0x401000 (unchanged).
    assert_eq!(
        image.entry.as_u64(),
        0x40_1000,
        "main entry was modified: {:#x}",
        image.entry.as_u64()
    );
}

/// Verify that the main binary's PT_LOAD segments are registered as VMAs
/// in the address space.
fn dynlinker_stub_main_segments_registered() {
    let (image, aspace) = load_dynlinked_elf();

    // The main binary has 2 PT_LOAD segments.
    assert_eq!(
        image.segments, 2,
        "expected 2 main-binary segments, got {}",
        image.segments
    );

    // Verify VMA coverage: 0x400000 (text) and 0x402000 (data) must be
    // findable in the address space.
    let text_vma = aspace.find(0x40_0000);
    assert!(
        text_vma.is_some(),
        "no VMA covers the main binary's text segment at 0x400000"
    );

    let data_vma = aspace.find(0x40_2000);
    assert!(
        data_vma.is_some(),
        "no VMA covers the main binary's data segment at 0x402000"
    );

    // image_end must be past the last segment (0x402000 + 0x1000 = 0x403000).
    assert!(
        image.image_end >= 0x40_3000,
        "image_end ({:#x}) should be >= 0x403000",
        image.image_end
    );

    serial_println!(
        "  main segments={} image_end={:#x}",
        image.segments,
        image.image_end
    );

    // Verify that interpreter segments are also registered: at least one
    // VMA should cover INTERP_LOAD_BASE.
    let interp_vma = aspace.find(INTERP_LOAD_BASE as usize);
    assert!(
        interp_vma.is_some(),
        "no VMA covers the interpreter at INTERP_LOAD_BASE ({:#x})",
        INTERP_LOAD_BASE
    );
    serial_println!("  interpreter VMA at {:#x} present", INTERP_LOAD_BASE);
}

/// Verify that the effective entry point (what `exec_atomic` would jump to)
/// is the interpreter's entry, not the main binary's.
fn dynlinker_stub_effective_entry_is_interp() {
    let (image, _aspace) = load_dynlinked_elf();

    let effective_entry = image.interp_entry.unwrap_or(image.entry);

    // The effective entry must differ from the main binary's entry —
    // exec_atomic would jump to the interpreter, not the main binary.
    assert_ne!(
        effective_entry.as_u64(),
        image.entry.as_u64(),
        "effective entry == main entry; interpreter not used"
    );

    // It must be within the interpreter's load range.
    assert!(
        effective_entry.as_u64() >= INTERP_LOAD_BASE,
        "effective entry ({:#x}) below INTERP_LOAD_BASE ({:#x})",
        effective_entry.as_u64(),
        INTERP_LOAD_BASE,
    );

    serial_println!(
        "  effective_entry={:#x} (interp), main_entry={:#x}",
        effective_entry.as_u64(),
        image.entry.as_u64()
    );
}
